<div class="bg-1nya">
    <div class="background-yellow">
        <div class="height-55">
        </div>
        <div class="bg-breadcrumb">
            <ol class="breadcrumb">
              <li><a href="<?php echo base_url() ;?>">HOME</a></li>
              &nbsp;&nbsp;>&nbsp;&nbsp;
              <li class="active">Syarat & Ketentuan Penggunaan</li>
            </ol>
        </div>
        <div class="mx-auto back-blok-rightcont-gold">
            <div class="container">
              <div class="row">
                <div class="col-md-12 about">
                    <h2>Syarat & Ketentuan Penggunaan</h2>
                    <hr>
                </div>
                <br>
                <br>
                <div class="col-md-12">
                  <p>Selamat datang di <a href="<?php echo base_url() ;?>">www.JuraganCash.com</a> dan / atau aplikasi <em>mobile</em>JuraganCash.</p>
                  <p><strong>Silahkan membaca Term of condition ini dengan seksama</strong>. </p>
                  <p>Syarat &amp; ketentuan yang ditetapkan di bawah ini mengatur pemakaian jasa yang ditawarkan oleh PT. JURAGAN CYBER GROUP terkait penggunaan situs <a href="<?php echo base_url() ;?>">www.JuraganCash.com</a> dan / atau aplikasi <em>mobile</em> JuraganCash.</p>
                  <p>Pengguna disarankan membaca dengan seksama Syarat dan Ketentuan dibawah ini karena dapat berdampak kepada hak dan kewajiban Pengguna di bawah hukum.</p>
                  <p>Dengan mengakses, mendaftar dan/atau menggunakan situs <a href="<?php echo base_url() ;?>">www.JuraganCash.com</a> dan / atau aplikasi <em>mobile</em> JuraganCash, maka pengguna dianggap telah membaca, mengerti, memahami dan menyetujui semua isi dalam Syarat &amp; Ketentuan ini. Syarat &amp; Ketentuan ini merupakan bentuk kesepakatan yang dituangkan dalam sebuah perjanjian yang sah antara Pengguna dengan PT.JURAGAN CYBER GROUP. Jika pengguna tidak menyetujui salah satu, sebagian, atau seluruh isi Syarat &amp; ketentuan ini, maka pengguna tidak diperkenankan mengakses, menggunakan, dan / atau mendaftar pada layanan di <a href="<?php echo base_url() ;?>">www.JuraganCash.com</a> dan / atau aplikasi <em>mobile</em>
                  JuraganCash.</p>
                  <p><strong>I. DEFINISI</strong></p>
                  <p>a. PT. JURAGAN CYBER GROUP adalah suatu perseroan terbatas yang menjalankan kegiatan usaha jasa web portal <a href="<?php echo base_url() ;?>">www.JuraganCash.com</a>, yaitu situs toko dan barang yang menjual berbagai macam produk berupa Voucher Game, Game, CD KEY, Game Console, Console, Pulsa, PPOB, Paket Data, Token PLN, Voucher dan berbagai macam produk game lainnya. Selanjutnya disebut JuraganCash.</p>
                  <p>b. Situs JuraganCash adalah <a href="<?php echo base_url() ;?>">www.JuraganCash.com</a></p><p>c. Syarat &amp; ketentuan adalah perjanjian antara Pengguna dan JuraganCash yang berisikan peraturan yang mengatur hak, kewajiban, tanggung jawab pengguna dan JuraganCash.</p>
                  <p>d. Pengguna adalah pihak yang menggunakan layanan situs JuraganCash dan / atau aplikasi <em>mobile</em> JuraganCash, termasuk namun tidak terbatas pada pembeli, penjual ataupun pihak lain yang sekedar berkunjung ke Situs JuraganCash.</p>
                  <p>e. Pembeli adalah Pengguna terdaftar yang melakukan pembelian atas Barang yang dijual oleh JuragamnCash di Situs JuraganCash.</p><p><strong>II. AKUN, SALDO JURAGANCASH, PASSWORD DAN KEAMANAN</strong></p>
                  <p>a. Pengguna dengan ini menyatakan bahwa pengguna adalah orang yang cakap dan mampu untuk mengikatkan dirinya dalam sebuah perjanjian yang sah menurut hukum.</p><p>b. JuraganCash tidak memungut biaya pendaftaran kepada Pengguna.</p>
                  <p>c. JuraganCash tanpa pemberitahuan terlebih dahulu kepada Pengguna, memiliki kewenangan untuk melakukan tindakan yang dikira perlu atas setiap dugaan pelanggaran atau pelanggaran Syarat &amp; ketentuan dan/atau hukum yang berlaku, yakni tindakan berupa pemblokiran akun pengguna, pembatalan pembelian, dan/atau penghapusan akun pengguna.</p>
                  <p>d. JuraganCash memiliki kewenangan penuh untuk meminta bukti transaksi berupa bukti transfer bank, bukti struk atm, screenshot bukti transfer guna untuk keperluan verifikasi data.</p>
                  <p>e. Apabila ditemukan kecurigaan, JuraganCash memiliki kewenangan penuh untuk meminta data Pengguna berupa foto KTP atau Kartu Identitas yang sah lainnya, foto Selfie Pengguna beserta KTPnya dan segala informasi yang dikira perlu untuk proses verifikasi data. Hal ini kami perlukan dikarenakan himbauan dari Bank Indonesia untuk bekerja sama  menerapkan KYC (Know Your Customer) dan AML (Anti Money Laundering)</p>
                  <p>f. Pengguna dilarang untuk menciptakan dan/atau menggunakan perangkat, <em>software, </em>fitur dan/atau alat lainnya yang bertujuan untuk melakukan manipulasi pada sistem JuraganCash, termasuk namun tidak terbatas pada : (i) manipulasi data akun; (ii) kegiatan perambanan (<em>crawling/scraping</em>); (iii) kegiatan otomatisasi dalam transaksi, jual beli, promosi, dsb; (iv) penambahan produk ke dalam situs; dan/atau (v) aktivitas lain yang secara wajar dapat dinilai sebagai tindakan manipulasi sistem JuraganCash.</p>
                  <p>g. Kegiatan terlarang: Pengguna setuju dan TIDAK boleh melakukan : </p>
                  <ol>
                   <li>Berpura-pura sebagai orang lain / entitas, atau      memberikan keterangan yang salah, atau mengaku sebagai orang lain atau      kelompok tertentu;</li>
                   <li>Mendaftar dengan data yang tidak sesuai KTP atau Kartu      Identitas yang sah;</li>
                   <li>Menggunakan situs JuraganCash dan / atau      aplikasi <em>mobile</em> JuraganCash      dengan tujuan yang melanggar hukum (illegal);</li>
                   <li>Berusaha untuk mendapatkan akses tidak sah atau      mengganggu atau mengacaukan sistem komputer atau jaringan yang terhubung      dengan situs JuraganCash dan / atau aplikasi <em>mobile</em> JuraganCash;</li>
                   <li>Mengganggu pemanfaatan dan pemakaian dari situs      JuraganCash dan      / atau aplikasi <em>mobile</em> JuraganCash;</li>
                   <li>Menggunakan atau unggah atau meng-<em>upload</em>
                     perangkat lunak (software) atau material yang mengandung / dicurigai      mengandung virus, komponen merusak, kode berbahaya atau komponen berbahaya      dengan cara apapun yang dapat merusak data atau mengakibatkan kerusakan situs      JuraganCash dan      / atau aplikasi <em>mobile</em> JuraganCash      atau mengganggu pengoperasian komputer Pelanggan lain atau situs      JuraganCash dan      / atau aplikasi <em>mobile</em> JuraganCash;</li>
                   <li>Menggunakan situs JuraganCash dan / atau      aplikasi <em>mobile</em> JuraganCash      diluar dari aturan / kebijakan penggunaan setiap jaringan komputer yang      terhubung, setiap standar Internet yang berlaku dan hukum yang berlaku      lainnya.</li>
                   <li>Menggunakan transaksi di situs JuraganCash dan / atau      aplikasi <em>mobile</em> JuraganCash untuk menipu orang lain atau pihak ketiga.</li>
                  </ol>
                  <p>h. JuraganCash memiliki kewenangan untuk melakukan pembekuan saldo JuraganCash pengguna apabila ditemukan / diduga adanya tindak kecurangan dalam bertransaksi dan/atau pelanggaran terhadap syarat dan ketentuan JuraganCash.</p>
                  <p>i. JuraganCash memiliki kewenangan penuh untuk menutup  akun Pengguna baik sementara maupun permanen apabila didapati adanya tindakan kecurangan dalam bertransaksi dan/atau pelanggaran terhadap syarat dan ketentuan JuraganCash.</p>
                  <p>j. Pengguna bertanggung jawab secara pribadi untuk menjaga kerahasiaan akun dan password untuk semua aktivitas yang terjadi dalam akun Pengguna.</p><p>k. Pengguna dilarang melakukan duplikasi situs JuraganCash, duplikasi produk JuraganCash, hacking situs JuraganCash atau tindakan-tindakan lain yang dapat diindikasikan sebagai usaha yang merugikan JuraganCash.</p>
                  <p>l. JuraganCash tidak akan pernah meminta username, password maupun kode SMS verifikasi atau kode PIN milik akun Pengguna untuk alasan apapun, oleh karena itu JuraganCash menghimbau Pengguna agar tidak memberikan data tersebut maupun data penting lainnya kepada pihak yang mengatasnamakan JuraganCash atau pihak lain yang tidak dapat dijamin keamanannya.</p>
                  <p>m. Pengguna setuju untuk memastikan bahwa Pengguna keluar (LOGOUT) dari akun di akhir setiap sesi dan segera memberitahu JuraganCash jika ada penggunaan tanpa izin atas sandi atau akun Pengguna.</p><p>n. Pengguna dengan ini menyatakan bahwa JuraganCash tidak bertanggung jawab atas kerugian ataupun kendala yang timbul atas penyalahgunaan akun Pengguna yang diakibatkan oleh kelalaian Pengguna, termasuk namun tidak terbatas pada meminjamkan atau memberikan akses akun kepada pihak lain, mengakses link atau tautan yang diberikan oleh pihak lain, memberikan atau memperlihatkan SMS Verifikasi, PIN, password atau email kepada pihak lain, maupun kelalaian Pengguna lainnya yang mengakibatkan kerugian ataupun kendala pada akun Pengguna.</p>
                  <p>o. Akses atas <em>password</em>, SMS Verifikasi, PIN pada situs JuraganCash dan/atau penggunaan Layanan dibatasi hanya untuk Pengguna yang memiliki akun saja. Pengguna tidak diperbolehkan memperoleh atau berusaha memperoleh akses tidak sah ke dalam situs JuraganCash dan / atau aplikasi <em>mobile</em>
                  JuraganCash atau ke area informasi lain yang dilindungi, dengan cara apapun yang tanpa ijin JuraganCash. Pelanggaran terhadap ketentuan ini merupakan pelanggaran yang didasarkan pada hukum Indonesia dan / atau undang-undang dan peraturan yang berlaku.</p>
                  <p>p. Saldo JuraganCash adalah layanan pembayaran yang disediakan oleh JuraganCash untuk memudahkan pengguna dalam bertransaksi di situs <strong>JuraganCash dan / atau aplikasi mobile JuraganCash.</strong></p>
                  <p><strong>q. </strong>Jika ada transaksi dari JuraganCash yang gagal atau stock produk habis, maka dana akan dikembalikan ke Saldo JuraganCash pengguna.</p>
                  <p>r. Saldo JuraganCash tidak dapat diuangkan atau ditransfer kembali ke rekening pengguna dengan alasan apapun.</p>
                  <p>s. JuraganCash berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila ditemukan tindakan manipulasi/kecurangan, seperti menutup akun, menarik saldo JuraganCash, menarik Point Reward, membatalkan transaksi, menahan dana, serta hal-hal lainnya jika ditemukan indikasi kecurangan atau pelanggaran pelanggaran Syarat dan Ketentuan JuraganCash dan ketentuan hukum yang berlaku di wilayah negara Indonesia.</p>
                  <p>t. <strong>Jika Pengguna berusia di bawah 18 tahun</strong><strong>:</strong>
                  Pengguna harus memperoleh persetujuan dari orang tua atau wali Pengguna. Orang tua/wali Pengguna harus setuju terhadap Syarat dan Ketentuan diatas &amp; serta persetujuan mereka untuk mengambil tanggung jawab untuk: (i) tindakan Pengguna dibawah 18 tahun; (ii) biaya yang terkait dengan penggunaan setiap Layanan atau pembelian Produk; dan (iii) penerimaan dan kepatuhan Anda sesuai dengan Syarat &amp; Ketentuan Penggunaan ini. <strong>Jika Anda tidak memiliki izin dari orang tua atau wali, Anda harus berhenti menggunakan / mengakses situs JuraganCash dan / atau aplikasi mobile JuraganCash dan berhenti menggunakan Layanan ini.</strong>
                  </p><p>u. Semua pengguna setuju untuk mematuhi setiap dan semua pedoman, pemberitahuan, aturan operasi dan kebijakan dan instruksi yang berkaitan dengan penggunaan Layanan dan/atau akses ke situs JuraganCash <strong>dan / atau aplikasi mobile JuraganCash, s</strong>erta setiap perubahan-nya, yang dikeluarkan oleh JuraganCash, dari waktu ke waktu. JuraganCash berhak untuk merevisi pedoman, pemberitahuan, aturan operasi, kebijakan dan instruksi sewaktu-waktu dan Pengguna dianggap mengetahui dan tunduk oleh setiap perubahan tersebut di atas setelah ada-nya pemberitahuan atau publikasi atas perubahan tersebut di situs JuraganCash dan atau aplikasi mobile JuraganCash atau pemberitahuan melalui media lain.</p>
                  <p>v. Dalam hal ditemukan adanya dugaan pelanggaran terhadap Syarat dan Ketentuan JuraganCash, kecurangan, manipulasi atau kejahatan, Pengguna memahami dan menyetujui bahwa JuraganCash berhak melakukan tindakan pemeriksaan, pembekuan, penundaan dan/atau pembatalan terhadap akun JuraganCash milik Pengguna.</p>
                  <p><strong>III. TRANSAKSI PEMBELIAN &amp; HARGA</strong></p>
                  <p>a. Pembeli wajib bertransaksi melalui prosedur transaksi yang telah ditetapkan oleh JuraganCash. Pembeli melakukan pembayaran dengan menggunakan metode pembayaran yang sebelumnya telah dipilih oleh Pembeli. Dan kemudian setelah terverifikasi, maka JuraganCash akan menambahkan dana ke Saldo JuraganCash.</p>
                  <p>b. Pembeli disarankan membayar sendiri seluruh tagihannya menggunakan akun pribadi banknya untuk memudahkan proses verifikasi data pada saat diminta oleh JuraganCash.</p>
                  <p>c. Pembeli atau pengguna dilarang menggunakan Nomor rekening dan / atau nomor Virtual Account milik JuraganCash untuk menipu pihak lain. Apabila ditemukan kecurangan, JuraganCash berhak untuk memblokir akun yang bersangkutan.</p><p>d. Pengguna atau Pembeli dilarang untuk menipu atau berusaha mengelabui pihak lain untuk melakukan pembayaran atas tagihan yang dibuat. Karena masing" nomor Virtual Account dan tagihan hanya boleh diketahui oleh Pengguna pribadi. Segala bentuk kerugian akibat bocornya informasi Nomor Rekening, Nomor Virtual Account, Jumlah tagihan, dll tersebut merupakan tanggung jawab pribadi sepenuhnya dari Pengguna atau Pembeli. Apabila ditemukan kecurangan, JuraganCash berhak untuk memblokir akun yang bersangkutan.</p>
                  <p>e. Pada saat melakukan pembelian barang, pembeli menyetujui bahwa : </p>
                  <p>            1. Pembeli bertanggung jawab untuk membaca, memahami, dan menyetujui informasi/deskripsi keseluruhan sebelum membuat komitmen untuk membeli.</p>
                  <p>            2. Kesalahan membeli produk merupakan tanggungjawab Pembeli.Semua produk yang sudah dikirim oleh JuraganCash tidak bisa diRefund atau dikembalikan lagi dengan alasan apapun.</p>
                  <p>f. Pembeli memahami dan menyetujui bahwa ketersediaan stok Barang merupakan tanggung jawab JuraganCash. Terkait ketersediaan stok Barang dapat berubah sewaktu-waktu, sehingga dalam keadaan stok Barang kosong, maka JuraganCash berhak untuk menolak order, dan atau membatalkan order dan mengembalikan sisa pembayaran ke Saldo JuraganCash pada akun pembeli.</p>
                  <p>g. Pembeli memahami sepenuhnya dan menyetujui bahwa segala transaksi yang dilakukan diluar situs JuraganCash dan/atau tanpa sepengetahuan JuraganCash (melalui fasilitas/jaringan pribadi, pengiriman pesan, Whatsapp, LINE, Forum", pengaturan transaksi khusus diluar situs JuraganCash atau upaya lainnya) adalah merupakan tanggung jawab pribadi sepenuhnya dari Pembeli. JuraganCash dibebaskan dari segala bentuk kerugian yang ditimbulkan dan  tidak bisa dituntut ganti rugi dalam bentuk apapun.</p>
                  <p>h. JuraganCash memiliki kewenangan sepenuhnya untuk menolak pembayaran tanpa pemberitahuan terlebih dahulu.</p>
                  <p>i. Pembayaran oleh Pembeli wajib dilakukan segera (selambat-lambatnya dalam batas waktu 24 jam) setelah Pembeli mengisi Form TopUp dan mendapatkan nomor Virtual Account. Jika dalam batas waktu tersebut pembayaran atau konfirmasi pembayaran belum dilakukan oleh pembeli, JuraganCash memiliki kewenangan untuk membatalkan transaksi dimaksud. Pengguna tidak berhak mengajukan klaim atau tuntutan atas pembatalan transaksi tersebut.</p>
                  <p>j. Konfirmasi pembayaran dengan setoran tunai wajib disertai dengan berita pada slip setoran berupa nomor pembayaran dan nama. Konfirmasi pembayaran dengan setoran tunai tanpa keterangan tidak akan diproses oleh JuraganCash.</p>
                  <p>k. Pembeli menyetujui untuk tidak memberitahukan atau menyerahkan bukti pembayaran dan/atau data pembayaran kepada pihak lain selain JuraganCash. Dalam hal terjadi kerugian akibat pemberitahuan atau penyerahan bukti pembayaran dan/atau data pembayaran oleh Pembeli kepada pihak lain, maka hal tersebut akan menjadi tanggung jawab Pembeli.</p>
                  <p>l. JuraganCash memberikan batas waktu 2 (dua) hari sejak barang berstatus "COMPLETE" untuk pembeli  melakukan komplain. Jika dalam batas waktu tersebut tidak ada konfirmasi atau klaim dari pihak Pembeli, maka dengan demikian Pembeli menyatakan Barang yang sudah dibeli dapat digunakan dan tidak ada masalah sama sekali.</p>
                  <p>m. Pembeli memahami dan menyetujui bahwa setiap klaim atau komplain yang dilayangkan setelah lebih dari 2 (dua) hari adalah bukan menjadi tanggung jawab JuraganCash. Kerugian yang timbul setelah lebih dari 2 (dua) hari menjadi tanggung jawab Pembeli secara pribadi.</p>
                  <p>n. Pembeli memahami dan menyetujui bahwa biaya tambahan yang disebabkan oleh perbedaan bank yang Pembeli pergunakan dengan bank Rekening resmi JuraganCash adalah tanggung jawab Pembeli secara pribadi.</p>
                  <p>o. Pengembalian dana dari JuraganCash kepada Pembeli hanya dapat dilakukan jika dalam keadaan-keadaan tertentu berikut ini : </p>
                  <p>            1. JuraganCash tidak bisa menyanggupi atau mengirimkan Barang yang dibeli dikarenakan Stock Habis.</p>
                  <p>            2. Keterlambatan pengiriman barang dari Supplier sehingga JuraganCash terlambat mengirimkan barang ke Pembeli.</p>
                  <p>p. Apabila terjadi proses pengembalian dana, maka pengembalian dana akan dilakukan melalui Saldo JuraganCash milik Pengguna. Saldo JuraganCash pengguna akan bertambah sesuai dengan jumlah pengembalian dana.</p>
                  <p>q. JuraganCash berwenang mengambil keputusan atas permasalahan-permasalahan transaksi yang belum terselesaikan akibat kurangnya bukti" kuat dari Pembeli. Keputusan JuraganCash adalah keputusan akhir yang tidak dapat diganggu gugat dan mengikat pihak Pembeli untuk mematuhinya.</p>
                  <p>r. Pembeli wajib melakukan pembayaran dengan nominal yang sesuai dengan jumlah tagihan yang tertera pada halaman pembayaran. JuraganCash tidak bertanggungjawab atas kerugian yang dialami Pembeli apabila melakukan pembayaran yang tidak sesuai dengan jumlah tagihan yang tertera pada halaman pembayaran.</p>
                  <p>s. JuraganCash memiliki wewenang untuk merubah harga Barang sewaktu - waktu tanpa pemberitahuan sebelumnya.</p>
                  <p>t. JuraganCash menjamin kerahasiaan dan keamanan voucher yang telah dibeli termasuk perlindungan terhadap usaha penyalahgunaan wewenang dan/atau jabatan dari administrator/ pegawai/ staff kami.</p>
                  <p>u. Harga Barang yang terdapat dalam situs JuraganCash dan / atau aplikasi mobile JuraganCash adalah harga yang ditetapkan oleh JuraganCash. Pengguna atau Pembeli dilarang memanipulasi harga barang dengan cara apapun.</p>
                  <p>v. Pembeli memahami dan menyetujui bahwa kesalahan keterangan harga dan informasi lainnya yang disebabkan tidak terbaharuinya halaman situs JuraganCash dikarenakan browser/ISP yang dipakai Pembeli adalah tanggung jawab Pembeli.</p>
                  <p>w. Dengan melakukan pembelian melalui situs JuraganCash dan / atau aplikasi mobile JuraganCash, Pengguna menyetujui untuk membayar total biaya yang harus dibayarkan sebagaimana tertera dalam halaman pembayaran, yang terdiri dari harga barang, dan biaya-biaya lain yang mungkin timbul dan akan diuraikan secara tegas dalam halaman pembayaran. Pengguna setuju untuk melakukan pembayaran melalui metode pembayaran yang telah dipilih sebelumnya oleh Pengguna.</p>
                  <p>x. situs JuraganCash dan / atau aplikasi mobile JuraganCash untuk saat ini hanya melayani transaksi jual beli Barang dalam mata uang Rupiah.</p>
                  <p><strong>IV. PERSYARATAN PENGGUNAAN UMUM </strong></p>
                  <p>a. Dengan ini  pengguna setuju: untuk selalu mengakses dan/atau menggunakan situs JuraganCash dan / atau aplikasi mobile JuraganCash hanya untuk tujuan yang tidak melanggar hukum, dan dengan cara yang sah dan selanjutnya setuju untuk melakukan kegiatan yang berkaitan dengan dengan itikad baik.</p>
                  <p>b. Deskripsi Produk: Voucher yang dijual oleh JuraganCash adalah voucher yang dapat digunakan untuk melakukan pembayaran ke perusahaan penyedia jasa game online maupun platform lainnya</p>
                  <p>c. Jika pada saat Pengguna melakukan konfirmasi pembayaran, terjadi gangguan komunikasi antara JuraganCash dan Bank ataupun channel pembayaran lain nya, Pengguna dapat mencoba kembali sampai berhasil. Jika dalam beberapa kali proses konfirmasi selalu gagal, Pengguna dapat menghubungi customer service kami untuk dibantu permasalahan yang terjadi.</p>
                  <p>d. JuraganCash adalah portal web yang menyediakan berbagai macam produk berupa Voucher Game, Game, CD KEY, Game Console, Pulsa, PPOB, Paket Data, Token PLN dan berbagai macam produk game lainnya kepada Pengguna untuk dapat melakukan pembelian di website JuraganCash. Dengan demikian Pengguna memahami bahwa batasan tanggung jawab JuraganCash secara proporsional adalah sebagai penyedia jasa portal web</p><p>e. JuraganCash selalu berupaya untuk menjaga Layanan JuraganCash aman, nyaman, dan berfungsi dengan baik, tapi kami tidak dapat menjamin operasi terus-menerus atau akses ke Layanan kami dapat selalu sempurna. Informasi dan data dalam situs JuraganCash memiliki kemungkinan tidak terjadi secara real time.</p>
                  <p>f. Pengguna setuju bahwa pengguna memanfaatkan Layanan JuraganCash atas risiko Pengguna sendiri.</p>
                  <p>g. Sesuai dengan hukum yang berlaku, JuraganCash (termasuk Induk Perusahaan, direktur, dan karyawan) tidak bertanggung jawab, dan Pengguna setuju untuk tidak menuntut JuraganCash bertanggung jawab, atas segala kerusakan atau kerugian (termasuk namun tidak terbatas pada hilangnya uang,  keuntungan, atau kerugian tak berwujud lainnya) yang diakibatkan secara langsung atau tidak langsung dari :</p>
                  <ul>
                  <li>- Penggunaan atau ketidakmampuan Pengguna dalam      menggunakan situs JuraganCash dan / atau Aplikasi Mobile JuraganCash.</li>
                  <li>- Keterlambatan atau gangguan dalam Layanan JuraganCash.</li>
                  <li>- Kelalaian dan kerugian yang ditimbulkan oleh      masing-masing Pengguna.</li>
                  <li>- Kualitas Barang.</li>
                  <li>- Pengiriman Barang.</li>
                  <li>- Pelanggaran Hak atas Kekayaan Intelektual.</li>
                  <li>- Perselisihan.</li>
                  <li>- Pencemaran nama baik pihak lain.</li>
                  <li>- Setiap penyalahgunaan Barang yang sudah dibeli pihak      Pengguna.</li>
                  <li>- Kerugian akibat pembayaran tidak resmi kepada pihak      lain selain ke Rekening Resmi JuraganCash, yang dengan cara apa pun      mengatas-namakan JuraganCash ataupun kelalaian penulisan rekening dan/atau      informasi lainnya dan/atau kelalaian pihak bank.</li>
                  <li>- Virus atau perangkat lunak berbahaya lainnya (<em>bot,      script, automation tool</em>, <em>hacking tool</em>) yang diperoleh dengan      mengakses, atau menghubungkan ke layanan JuraganCash.</li>
                  <li>- Gangguan, bug, kesalahan atau ketidakakuratan apapun      dalam Layanan JuraganCash.</li>
                  <li>- Kerusakan pada perangkat keras Anda dari penggunaan      setiap Layanan JuraganCash.</li>
                  <li>- Isi, tindakan, atau tidak adanya tindakan dari pihak      ketiga, termasuk terkait dengan Produk yang ada dalam situs JuraganCash      yang diduga palsu.</li>
                  <li>- Tindak penegakan yang diambil sehubungan dengan akun      Pengguna.</li>
                  <li>- Adanya tindakan peretasan yang dilakukan oleh pihak      ketiga kepada akun pengguna.</li>
                  </ul>
                  <p>h. Pengguna melepaskan JuraganCash (termasuk Induk Perusahaan, Direktur, dan karyawan) dari klaim dan tuntutan atas kerusakan dan kerugian (aktual dan tersirat) dari setiap jenis dan sifatnya , yang dikenal dan tidak dikenal, yang timbul dari atau dengan cara apapun. Dengan demikian maka Pengguna dengan sengaja melepaskan segala perlindungan hukum (yang terdapat dalam undang-undang atau peraturan hukum yang lain) yang akan membatasi cakupan ketentuan pelepasan ini.</p>
                  <p>i. Pengguna akan melepaskan JuraganCash dari tuntutan ganti rugi dan menjaga JuraganCash (termasuk Induk Perusahaan, direktur, dan karyawan) dari setiap klaim atau tuntutan, termasuk biaya hukum yang wajar, yang dilakukan oleh pihak ketiga yang timbul dalam hal Anda melanggar Perjanjian ini, penggunaan Layanan JuraganCash yang tidak semestinya dan/ atau pelanggaran Anda terhadap hukum atau hak-hak pihak ketiga.</p>
                  <p>j. Perjanjian ini akan diatur oleh dan ditafsirkan sesuai dengan hukum Republik Indonesia, tanpa memperhatikan pertentangan aturan hukum. Anda setuju bahwa tindakan hukum apapun atau sengketa yang mungkin timbul dari, berhubungan dengan, atau berada dalam cara apapun berhubungan dengan situs dan/atau Perjanjian ini akan diselesaikan secara eksklusif dalam yurisdiksi pengadilan Republik Indonesia.</p>
                  <p>k. Syarat &amp; ketentuan mungkin di ubah dan/atau diperbaharui dari waktu ke waktu tanpa pemberitahuan sebelumnya. JuraganCash menyarankan agar Pengguna membaca secara seksama dan memeriksa halaman Syarat &amp; ketentuan ini dari waktu ke waktu untuk mengetahui perubahan apapun. Dengan tetap mengakses dan menggunakan layanan JuraganCash, maka pengguna dianggap menyetujui perubahan-perubahan dalam Syarat &amp; ketentuan.</p>
                </div>

              </div>
            </div>
        </div>
        <div class="mx-auto backbottom-right-contgold">
        </div>
        <div class="height-55">
        </div>
    </div>
</div>
